version: '3.1'

services:
  db:
    image: mysql:8.0.13
    restart: always
    volumes:
      - .:/docker-entrypoint-initdb.d
      - /storage/docker/mysql-wordnet-db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordnet
    ports:
      - "33366:3306"

  quarkus:
    build:
      context: ./wordnetloom-server
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-server
    restart: always
    depends_on:
      - db
    environment:
      WAIT_HOSTS: mysql:3306
    ports:
      - "8080:8080"
    links:
      - db:db

  maven:
    build:
      context: .
      dockerfile: maven.dockerfile
    container_name: maven
    volumes:
      - .:/wordnetloom
    working_dir: /wordnetloom
    entrypoint: [ 'mvn' ]

  jlink:
    build:
      context: .
      dockerfile: maven.dockerfile
    container_name: jlink
    volumes:
      - .:/wordnetloom
    working_dir: /wordnetloom
    entrypoint: [ 'jlink' ]

  jpackager:
    build:
      context: .
      dockerfile: maven.dockerfile
    container_name: jpackager
    volumes:
      - .:/wordnetloom
    working_dir: /wordnetloom
    entrypoint: [ '/packager/jpackager' ]

volumes:
  db_data: